"""remove the happend column

Revision ID: 45fc6340ee83
Revises: f2ddea0fb08b
Create Date: 2021-02-21 05:51:14.837729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fc6340ee83'
down_revision = 'f2ddea0fb08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'happened')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('happened', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
