"""to submite 

Revision ID: 567e0e32a06d
Revises: b8383cb0ad5b
Create Date: 2021-02-21 19:31:02.655742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567e0e32a06d'
down_revision = 'b8383cb0ad5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###
