"""to submite 

Revision ID: 935f33cd9f39
Revises: 3d584e52bd6c
Create Date: 2021-02-21 20:06:54.857955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935f33cd9f39'
down_revision = '3d584e52bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('facebook_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'facebook_link')
    # ### end Alembic commands ###
