"""to submite 

Revision ID: b8383cb0ad5b
Revises: 45fc6340ee83
Create Date: 2021-02-21 19:29:56.875111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8383cb0ad5b'
down_revision = '45fc6340ee83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
